-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 03/12/2024 às 01:40
-- Versão do servidor: 10.4.32-MariaDB
-- Versão do PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `projeto_carros`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `carros`
--

CREATE TABLE `carros` (
  `id_carros` int(11) NOT NULL,
  `modelo_carros` varchar(50) DEFAULT NULL,
  `marca_carros` varchar(30) DEFAULT NULL,
  `ano_carros` varchar(4) DEFAULT NULL,
  `preco_carros` decimal(15,2) DEFAULT NULL,
  `categoria_carros` varchar(30) DEFAULT NULL,
  `imagem_carros` varchar(600) DEFAULT NULL,
  `cor_carros` varchar(30) DEFAULT NULL,
  `descricao_carros` varchar(500) DEFAULT NULL,
  `promocao` tinyint(4) DEFAULT NULL COMMENT 'true = 1\n\nfalse = 0',
  `classe_carros` varchar(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `carros`
--

insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("911", "Porsche", "2019", 340000, "Esportivo", "https://upload.wikimedia.org/wikipedia/commons/c/c6/2013_Porsche_911_Carrera_4S_%28991%29_%289626546987%29.jpg", "Preto", "Porsche 911 Esportivo modelo 2019, por apenas R$340000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("3008", "Peugeot", "2023", 150000, "SUV", "https://garagem360.com.br/wp-content/uploads/2023/01/Peugeot-3008-Griffe-2023-4.jpg", "Preto", "Peugeot 3008 SUV modelo 2023, por apenas R$150000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("296 GTB", "Ferrari", "2023", 4000000, "Esportivo", "https://miamiimports.com.br/wp-content/uploads/2024/07/FERRARI-296-GTB-PRETA-DIANTEIRA-ESQUERDA.png", "Preto", "Ferrari 296 GTB Esportivo modelo 2023, por apenas R$4000000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("488 GTB", "Ferrari", "2016", 3000000, "Esportivo", "https://s3.ecompletocarros.dev/images/lojas/285/veiculos/200410/veiculoInfoVeiculoImagesMobile/vehicle_image_1720048538_d41d8cd98f00b204e9800998ecf8427e.jpeg", "Vermelho", "Ferrari 488 GTB Esportivo modelo 2016, por apenas R$3000000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("500 Elétrico", "Fiat", "2023", 140000, "Elétrico", "https://500e.fiat.com.br/content/dam/fiat/products/332/312/0/2022/page/hero.png", "Branco", "Fiat 500 Elétrico Elétrico modelo 2023, por apenas R$140000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("718 Cayman GT4 RS", "Porsche", "2023", 1230000, "Esportivo", "https://cdn.motor1.com/images/mgl/2NOO64/s1/2022-porsche-718-cayman-gt4-rs.webp", "Cinza", "Porsche 718 Cayman GT4 RS Esportivo modelo 2023, por apenas R$1230000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("720S", "McLaren", "2017", 4000000, "Esportivo", "https://cdn.wheel-size.com/automobile/body/mclaren-720s-2017-2023-1692949874.4686553.jpg", "Laranja", "McLaren 720S Esportivo modelo 2017, por apenas R$4000000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("911 GT3", "Porsche", "2021", 2500000, "Esportivo", "https://www.google.com/url?sa=i&url=https%3A%2F%2Fquatrorodas.abril.com.br%2Ftestes%2Fteste-porsche-911-gt3-e-um-esportivo-de-rua-com-vocacao-para-as-pistas&psig=AOvVaw2vj1tfQzAvOLUZ0LAo4rjb&ust=1732884976910000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCIih_N-J_4kDFQAAAAAdAAAAABAQ", "Azul", "Porsche 911 GT3 Esportivo modelo 2021, por apenas R$2500000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("A3", "Audi", "2006", 40000, "Hatch", "https://hips.hearstapps.com/hmg-prod/amv-prod-cad-assets/images/04q4/267353/2006-audi-a3-photo-9224-s-original.jpg", "Branco", "Audi A3 Hatch modelo 2006, por apenas R$40000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("A4", "Audi", "2021", 115000, "Sedan", "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgMv-RmISLLHmn-kCCNZYpXhv3hCnWyj5Z8W0MvK5KgPrr4FFu_AxxBUT3TenO6Hyy75CRgyeOGUHpyWm_YKIBQlEMRaXxqAl-lli8Aj_DiAdtm56kfCpD6MVdMIWGou9v1DVglhR51wHZL/s1600/Novo-Audi-A4-2021+%252826%2529.jpg", "Preto", "Audi A4 Sedan modelo 2021, por apenas R$115000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Amarok Comfortline", "Volkswagen", "2023", 210000, "Picape", "https://cdn.motor1.com/images/mgl/koomAx/s1/volkswagen-amarok-comfortline-v6-2022.jpg", "Branco", "Volkswagen Amarok Comfortline Picape modelo 2023, por apenas R$210000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Argo", "Fiat", "2023", 48000, "Hatch", "https://cdn.motor1.com/images/mgl/P3oyxA/s3/fiat-argo-trekking-1.3-cvt-2023.jpg", "Vermelho", "Fiat Argo Hatch modelo 2023, por apenas R$48000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Argo Drive", "Fiat", "2021", 50000, "Hatch", "https://cdn.motor1.com/images/mgl/P3oyxA/s3/fiat-argo-trekking-1.3-cvt-2023.jpg", "Vermelho", "Fiat Argo Drive Hatch modelo 2021, por apenas R$50000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Artura", "McLaren", "2023", 3500000, "Esportivo", "https://mclaren.scene7.com/is/image/mclaren/P16SilverS34thFront_2?wid=1728&hei=972", "Prata", "McLaren Artura Esportivo modelo 2023, por apenas R$3500000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Bonneville T100", "Triumph", "2022", 60000, "Classic", "https://production.autoforce.com/uploads/version/profile_image/7170/model_main_webp_comprar-jet-black_d1a2b0717f.png.webp", "Preto", "Triumph Bonneville T100 Classic modelo 2022, por apenas R$60000!", 0, "MOTO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("C4 Cactus", "Citröen", "2023", 100000, "Hatch", "https://cdn.motor1.com/images/mgl/eobY66/s3/f3_refresh_n2_nacre_3_5x8_front_arg_roda-diamantada.jpg", "Prata", "Citröen C4 Cactus Hatch modelo 2023, por apenas R$100000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("C4 Cactus Feel", "Citroën", "2023", 90000, "Hatch", "https://production.autoforce.com/uploads/version/profile_image/8180/model_main_webp_comprar-feel-1-6-automatico_35c6c79e76.png.webp", "Prata", "Citroën C4 Cactus Feel Hatch modelo 2023, por apenas R$90000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("C4 Picasso", "Citroen", "2020", 95000, "SUV", "https://s2-autoesporte.glbimg.com/ByWBQ8B7cubjh72RzWiRJHN01-k=/0x0:2035x1364/1008x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2019/1/m/Wvmjt0QcyJlGaI8gdxiQ/citroen-c4-picasso-33.jpg", "Azul", "Citroen C4 Picasso SUV modelo 2020, por apenas R$95000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("C5 Aircross", "Citroën", "2021", 160000, "SUV", "https://i0.statig.com.br/bancodeimagens/d1/by/6q/d1by6qa8fyx1jbbqky8nsuwc0.jpg", "Branco", "Citroën C5 Aircross SUV modelo 2021, por apenas R$160000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Camaro", "Chevrolet", "2023", 450900, "Esportivo", "https://image.webmotors.com.br/_fotos/anunciousados/gigante/2024/202405/20240516/chevrolet-camaro-6.2-v8-gasolina-ss-conversivel-automatico-wmimagem14321242479.jpg?s=fill&w=1920&h=1440&q=75", "Preto", "Chevrolet Camaro Esportivo modelo 2023, por apenas R$450900!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Camaro", "Chevrolet", "2021", 280000, "Esportivo", "https://i0.statig.com.br/bancodeimagens/1l/to/3s/1lto3s9pa82cyyx1uk8rwqx6t.jpg", "Vermelho", "Chevrolet Camaro Esportivo modelo 2021, por apenas R$280000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Captur", "Renault", "2021", 125000, "SUV", "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiLS0tbjOnbPlvHBsUhNEEopJOm-TR3WN8Nl9t8kjcPvhmO0k8bcvg87-fapYjiXJK4EtwSdPgqE2XA2CG9ZSsjaBQhAoEdp854xw5AykA4YtOvL3NOOL3CviS0AZQmHgfiluHHpT03bYT6/s1600/Novo-Captur-2021+%25281%2529.jpg", "Azul", "Renault Captur SUV modelo 2021, por apenas R$125000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Captur Iconic", "Renault", "2023", 135000, "SUV", "https://hips.hearstapps.com/hmg-prod/images/02-ss300p-3i4-front-1567937037.jpg?crop=0.671xw:1.00xh;0.161xw,0&resize=768:*", "Preto", "Renault Captur Iconic SUV modelo 2023, por apenas R$135000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Captur Intense", "Renault", "2021", 130000, "SUV", "https://generauto.com.br/wp-content/uploads/2024/10/cf2b8c2d4e9e4d379a8bd0c4e87b6ea0_1712088528573.jpeg", "Cinza", "Renault Captur Intense SUV modelo 2021, por apenas R$130000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("CB 500X", "Honda", "2022", 40000, "Adventure", "https://www.motonline.com.br/noticia/wp-content/uploads/2021/09/nova-cb-500-x-2022-1.jpg", "Preto", "Honda CB 500X Adventure modelo 2022, por apenas R$40000!", 1, "MOTO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Centodieci", "Bugatti", "2022", 43000000, "Superesportivo", "https://cdn.motor1.com/images/mgl/A8nvW/s1/bugatti-centodieci-a-molsheim.jpg", "Branco", "Bugatti Centodieci Superesportivo modelo 2022, por apenas R$43000000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("CG 150 Titan", "Honda", "2023", 15000, "Street", "https://carroslancamentos.com.br/wp-content/uploads/2014/08/moto-nova-cg-titan-150.jpg", "Vermelho", "Honda CG 150 Titan Street modelo 2023, por apenas R$15000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Challanger", "Dodge", "2023", 1180000, "Espotivo", "https://image.webmotors.com.br/_fotos/anunciousados/gigante/2024/202411/20241118/dodge-challenger-6-4-v8-hemi-gasolina-rt-scat-pack-widebody-torqueflite-wmimagem20441643817.webp?s=fill&w=1920&h=1440&q=75", "Preto", "Dodge Challanger Espotivo modelo 2023, por apenas R$1180000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Chevette", "Chevrolet", "1977", 65000, "Reliquias", "https://quatrorodas.abril.com.br/wp-content/uploads/2019/11/hr_8387.cr2_-e1574446155118.jpg?quality=70&strip", "Dourado", "Chevrolet Chevette Reliquias modelo 1977, por apenas R$65000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Chiron", "Bugatti", "2020", 50000000, "Superesportivo", "https://cdn.motor1.com/images/mgl/yKoGo/s1/bugatti-chiron-pur-sport-2020.jpg", "Azul", "Bugatti Chiron Superesportivo modelo 2020, por apenas R$50000000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Citroën Ami", "Citroën", "2023", 70000, "Elétrico", "https://cdn.motor1.com/images/mgl/JPoz4/s1/citroen-ami-2020.jpg", "Prata", "Citroën Citroën Ami Elétrico modelo 2023, por apenas R$70000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("City", "Honda", "2021", 75000, "Sedan", "https://plazamotors.com.br/uploads/products/versions/colors/3-4-frontal-lado-a-honda-city-touring-basicas-f01-azul-cosmico-300dpi.png", "Azul", "Honda City Sedan modelo 2021, por apenas R$75000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Civic", "Honda", "2021", 120000, "Sedan", "https://image1.mobiauto.com.br/images/api/images/v1.0/188131642/transform/t_crop", "Preto", "Honda Civic Sedan modelo 2021, por apenas R$120000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Civic Touring", "Honda", "2021", 135000, "Sedan", "https://img0.icarros.com/dbimg/galeriaimgmodelo/7/124443_1.jpg", "Branco", "Honda Civic Touring Sedan modelo 2021, por apenas R$135000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Civic Type R", "Honda", "2023", 250000, "Esportivo", "https://cdn.motor1.com/images/mgl/ojmQx7/s1/esportivos-fiat-pulse-abarth-vw-jetta-gli-e-honda-civic-type-r.webp", "Azul", "Honda Civic Type R Esportivo modelo 2023, por apenas R$250000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Compass", "Jeep", "2022", 160000, "SUV", "https://canalcarro.net.br/wp-content/uploads/2023/05/Jeep-Compass-2021.webp", "Azul marinho", "Jeep Compass SUV modelo 2022, por apenas R$160000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Compass Limited", "Jeep", "2022", 175000, "SUV", "https://www.webmotors.com.br/wp-content/uploads/2021/04/28101024/Jeep-Compass-2022-Limited-3.jpeg", "Vinho", "Jeep Compass Limited SUV modelo 2022, por apenas R$175000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Compass Trailhawk", "Jeep", "2023", 190000, "SUV", "https://quatrorodas.abril.com.br/wp-content/uploads/2021/04/jeep_compass_trailhawk_4xe_83.jpeg?crop=1&resize=1212,909", "Vermelho", "Jeep Compass Trailhawk SUV modelo 2023, por apenas R$190000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Cooper Elétrico", "Mini", "2023", 250000, "Elétrico", "https://motorshow.com.br/wp-content/uploads/sites/2/2021/12/mini-cooper-se-frs-1-1024x768-1.jpg", "Verde", "Mini Cooper Elétrico Elétrico modelo 2023, por apenas R$250000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Corolla", "Toyota", "2022", 100000, "Sedan", "https://www.comprecar.com.br/blog/wp-content/uploads/2020/12/Corolla.png", "Branco", "Toyota Corolla Sedan modelo 2022, por apenas R$100000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Corolla Altis", "Toyota", "2022", 110000, "Sedan", "https://revistacarro.com.br/wp-content/uploads/2024/01/WhatsApp-Image-2024-01-24-at-10.45.42.jpeg", "Prata", "Toyota Corolla Altis Sedan modelo 2022, por apenas R$110000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Corolla Cross", "Toyota", "2023", 140000, "SUV", "https://mundodoautomovelparapcd.com.br/wp-content/uploads/2022/03/Toyota-Corolla-Cross-XRV-Hybrid-2023.jpg", "Branco", "Toyota Corolla Cross SUV modelo 2023, por apenas R$140000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Corsa", "Chevrolet", "2008", 22200, "Sedan", "https://image.webmotors.com.br/_fotos/anunciousados/gigante/2024/202411/20241125/chevrolet-corsa-1-4-mpfi-maxx-8v-flex-4p-manual-wmimagem12061687740.webp?s=fill&w=1920&h=1440&q=75", "Preto", "Chevrolet Corsa Sedan modelo 2008, por apenas R$22200!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Creta", "Hyundai", "2020", 110000, "SUV", "https://cdn.autopapo.com.br/box/uploads/2020/05/13115606/frente-do-hyundai-creta-action-1.6-branco.jpg", "Prata", "Hyundai Creta SUV modelo 2020, por apenas R$110000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Creta Platinum", "Hyundai", "2023", 115000, "SUV", "https://s2-autoesporte.glbimg.com/YO9fvUz8qwSIBhK-DMx0xlmXfPc=/0x0:1080x607/888x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2023/L/H/msIuRCTsW4ilsIw3ZtIQ/hyundai-creta-platnum-safety.png", "Branco", "Hyundai Creta Platinum SUV modelo 2023, por apenas R$115000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Cronos", "Fiat", "2020", 55000, "Sedan", "https://quatrorodas.abril.com.br/wp-content/uploads/2021/07/Fiat-Cronos-169.jpg?quality=70&strip=info&w=720&crop=1", "Preto", "Fiat Cronos Sedan modelo 2020, por apenas R$55000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Cronos Drive", "Fiat", "2020", 55000, "Sedan", "https://cdn.motor1.com/images/mgl/WEX9o/s1/fiat-cronos-drive-1-8-at-2019.webp", "Branco", "Fiat Cronos Drive Sedan modelo 2020, por apenas R$55000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("CX-30", "Mazda", "2023", 140000, "SUV", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6QzmKjPtGSE1omBNFSbOR65p74L0NT9q6ww&s", "Preto", "Mazda CX-30 SUV modelo 2023, por apenas R$140000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("CX-5", "Mazda", "2022", 165000, "SUV", "https://media-assets.mazda.eu/image/upload/q_auto,f_auto/mazdapt/globalassets/cars/2023-mazda-cx-5/clearcuts/mme_cx5_kdpweae_46v_7-8.png?rnd=492678", "Vermelho", "Mazda CX-5 SUV modelo 2022, por apenas R$165000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Cybertruck", "Tesla", "2024", 1250000, "Picape Elétrica", "https://startse-uploader.s3.us-east-2.amazonaws.com/medium_Design_sem_nome_2023_11_27_T154321_785_655e3825be.png", "Prata", "Tesla Cybertruck Picape Elétrica modelo 2024, por apenas R$1250000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Divo", "Bugatti", "2020", 29575000, "Superesportivo", "https://s2-autoesporte.glbimg.com/fy3g89GFrTIr7MsMwvwVBNSyFkE=/0x0:620x413/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2020/v/X/XgfgDhQhitrQ3ADEy37w/2018-08-24-bugatti-divo-37.jpeg", "Preto", "Bugatti Divo Superesportivo modelo 2020, por apenas R$29575000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Duster", "Renault", "2023", 100000, "SUV", "https://cdn.motor1.com/images/mgl/AkBLk9/s1/renault-duster-2023.webp", "Marrom", "Renault Duster SUV modelo 2023, por apenas R$100000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Duster Intense", "Renault", "2023", 125000, "SUV", "https://s3.ecompletocarros.dev/images/lojas/206/veiculos/55942/veiculoInfoVeiculoImagesMobile/vehicle_image_1616045915_d41d8cd98f00b204e9800998ecf8427e.jpeg", "Vermelho", "Renault Duster Intense SUV modelo 2023, por apenas R$125000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Duster Outsider", "Renault", "2023", 115000, "SUV", "https://cdn.motor1.com/images/mgl/L33kOQ/s1/renault-duster-oroch-outsider-1.3-turbo-2022.jpg", "Prata", "Renault Duster Outsider SUV modelo 2023, por apenas R$115000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("E Pace", "Jaguar ", "2024", 465000, "SUV", "https://s2-autoesporte.glbimg.com/cRfgB53G0kLEapqlYrrkXxd2b48=/0x0:1980x1230/924x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2023/F/R/1rqIDiSWKIDEZb1awxmQ/novo-jaguar-e-pace-com-motor-2.0-frente.jpg", "Azul", "Jaguar  E Pace SUV modelo 2024, por apenas R$465000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("EB 110", "Bugatti", "1992", 12695000, "Superesportivo", "https://quatrorodas.abril.com.br/wp-content/uploads/2016/11/57ad055f0e2163719701bf362007-06-15_18_bugatti_eb_110_-bearb_-_kl.jpeg?crop=1&resize=1212,909", "Azul", "Bugatti EB 110 Superesportivo modelo 1992, por apenas R$12695000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("EcoSport", "Ford", "2022", 95000, "SUV", "https://image1.mobiauto.com.br/images/api/images/v1.0/284358523/transform/fl_progressive,f_webp,q_80", "Azul", "Ford EcoSport SUV modelo 2022, por apenas R$95000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("EcoSport SE", "Ford", "2023", 130000, "SUV", "https://image1.mobiauto.com.br/images/api/images/v1.0/49192200/transform/fl_progressive,f_webp,q_85,w_959", "Azul", "Ford EcoSport SE SUV modelo 2023, por apenas R$130000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Elantra", "Hyundai", "2023", 95000, "Sedan", "https://quatrorodas.abril.com.br/wp-content/uploads/2023/02/elantra-2024-e1677515141445.jpeg?crop=1&resize=1212,909", "Cinza", "Hyundai Elantra Sedan modelo 2023, por apenas R$95000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Elantra Sport", "Hyundai", "2023", 105000, "Sedan", "https://www.motortrend.com/uploads/2022/07/2023-Hyundai-Elantra-N-20-front-three-quarter-view.jpg", "Branco", "Hyundai Elantra Sport Sedan modelo 2023, por apenas R$105000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Escalade", "Cadilac", "2021", 1800000, "SUV", "https://www.cadillac.com/content/dam/cadillac/na/us/english/index/vehicles/2024/crossover-suvs/escalade/01-images/my24-escalade-mov-packages-onyx-v2.jpg?imwidth=1200", "Preto", "Cadilac Escalade SUV modelo 2021, por apenas R$1800000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("EV6", "Kia", "2023", 230000, "Elétrico", "https://hips.hearstapps.com/hmg-prod/images/2023-kia-ev6-gt-111-1659299283.jpg", "Prata", "Kia EV6 Elétrico modelo 2023, por apenas R$230000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Evija", "Lotus", "2023", 5000000, "Elétrico", "https://s2-autoesporte.glbimg.com/vd100eaje5s4MliRlG6h4AdMrFo=/0x0:620x413/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2020/k/V/jqNVeNQkKA3CnJMRZvuQ/2019-07-16-4-lotus-evija-front-3-4.jpg", "Prata", "Lotus Evija Elétrico modelo 2023, por apenas R$5000000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("F Type", "Jaguar ", "2024", 590000, "Superesportivo", "https://cdn.motor1.com/images/mgl/8AvK6M/s1/letzter-jaguar-f-type-2024.jpg", "Verde", "Jaguar  F Type Superesportivo modelo 2024, por apenas R$590000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Fiat Strada", "Fiat", "2023", 80000, "Picape", "https://quatrorodas.abril.com.br/wp-content/uploads/2022/07/strada-2023-5.jpg?crop=1&resize=1212,909", "Cinza", "Fiat Fiat Strada Picape modelo 2023, por apenas R$80000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Fiesta", "Ford", "2020", 90000, "Hatch", "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh2HYeigbws2cjGnOeIfM94zAA7XDSb4dZETQcLtZ1QLw27Effs9Z4WDo-_mxbj5n6dSfMU0YMzTPREocjxe9oeGvkMm-szq0upUGjQ2MUQQduIQCPevBa3drNz1PX-XFPipkIXYCH8yk0/s1600/Fiesta-ST-2020+%25282%2529.jpg", "Branco", "Ford Fiesta Hatch modelo 2020, por apenas R$90000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Fiesta Active", "Ford", "2023", 85000, "SUV", "https://s2.glbimg.com/h5DXQg8QTM5WANA3rdeEgdkio9E=/s.glbimg.com/jo/g1/f/original/2016/11/29/fiesta.jpg", "Laranja", "Ford Fiesta Active SUV modelo 2023, por apenas R$85000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Focus", "Ford", "2017", 70000, "Hatch", "https://static.wikia.nocookie.net/pedrofilms-inc/images/7/75/2018_Ford_Focus_ST-Line_X_1.0.jpg/revision/latest/scale-to-width-down/1200?cb=20210615132510&path-prefix=pt-br", "Azul", "Ford Focus Hatch modelo 2017, por apenas R$70000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Ford F-250", "Ford", "2022", 380000, "Picape", "https://www.automaistv.com.br/wp-content/uploads/2022/09/2023-Ford-F-Series-Super-Duty-10_edited.jpg", "Preto", "Ford Ford F-250 Picape modelo 2022, por apenas R$380000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("ForTwo", "Smart", "2023", 100000, "Elétrico", "https://cdn.wheel-size.com/automobile/body/smart-fortwo-2020-2025-1709710001.4421473.jpg", "Prata", "Smart ForTwo Elétrico modelo 2023, por apenas R$100000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Frontier", "Nissan", "2020", 170000, "Picape", "https://cdn.motor1.com/images/mgl/KqLgb/s1/nissan-frontier-2020-brasil.jpg", "Preto", "Nissan Frontier Picape modelo 2020, por apenas R$170000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Frontier XE-S", "Nissan", "2020", 185000, "Picape", "https://cdn.autopapo.com.br/box/uploads/2019/12/05103828/nissan-frontier-le-2020-frente.jpg", "Cinza", "Nissan Frontier XE-S Picape modelo 2020, por apenas R$185000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Fusca 1500", "VolksWagen", "1965", 130000, "Reliquias", "https://s3.sa-east-1.amazonaws.com/revista.mobiauto/Volkswagen/Fusca/VW-Fusca-dianteira.jpg", "Vermelho", "VolksWagen Fusca 1500 Reliquias modelo 1965, por apenas R$130000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("G 310 GS", "BMW", "2024", 38000, "Adventure", "https://production.autoforce.com/uploads/version/profile_image/8586/comprar-cosmic-black_b76062b5dc.png", "Preto", "BMW G 310 GS Adventure modelo 2024, por apenas R$38000!", 1, "MOTO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("G 310 R", "BMW", "2023", 30000, "Street", "https://www.powerbmw.com.br/wp-content/uploads/preta.png", "Preto", "BMW G 310 R Street modelo 2023, por apenas R$30000!", 0, "MOTO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Gemera", "Koenigsegg", "2023", 7000000, "Espotivo", "https://s2-autoesporte.glbimg.com/7xoebpLbauWR-QHroHyZbWN3eQU=/0x0:620x413/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2020/o/J/ACA4X8T9Gb5zwJ6pCZRA/2020-03-03-gemera.jpg", "Preto", "Koenigsegg Gemera Espotivo modelo 2023, por apenas R$7000000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Gol", "Volkswagen", "2023", 70000, "Hatch", "https://cdn.motor1.com/images/mgl/YAAopq/s1/volkswagen-gol-1.0-2023.jpg", "Branco", "Volkswagen Gol Hatch modelo 2023, por apenas R$70000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Golf", "VolksWagen", "2023", 240000, "Hatch", "https://image1.mobiauto.com.br/images/api/images/v1.0/377033790/transform/t_crop", "Preto", "VolksWagen Golf Hatch modelo 2023, por apenas R$240000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Golf GTI", "Volkswagen", "2020", 180000, "Hatch", "https://cdn.motor1.com/images/mgl/BMQEM/s1/2020-vw-golf-gti-rendering-lead-image.jpg", "Vermelho", "Volkswagen Golf GTI Hatch modelo 2020, por apenas R$180000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("GSX 125", "Suzuki", "2024", 16000, "Street", "https://images5.1000ps.net/images_bikekat/2024/3-Suzuki/8816-GSX_S125/005-638433353118029352-suzuki-gsx-s125.jpg?format=webp&quality=80&trim.threshold=80&trim.percentpadding=1&scale=both&width=1168&height=664&bgcolor=rgba_39_42_44_0&mode=pad", "Azul", "Suzuki GSX 125 Street modelo 2024, por apenas R$16000!", 0, "MOTO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("GT-R Nismo", "Nissan", "2020", 1500000, "Esportivo", "https://fotos-jornaldocarro-estadao.nyc3.cdn.digitaloceanspaces.com/uploads/2019/04/21122627/5ee03295-2020-nissan-gt-r-19-1160x773.jpg", "Branco", "Nissan GT-R Nismo Esportivo modelo 2020, por apenas R$1500000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("GTO Coupe", "Pontiac", "1969", 200000, "Reliquias", "https://lartbr.com.br/wp-content/webp-express/webp-images/uploads/2022/12/IMG_7908.jpg.webp", "Preto", "Pontiac GTO Coupe Reliquias modelo 1969, por apenas R$200000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("HB20", "Hyundai", "2022", 62000, "Hatch", "https://fotos-jornaldocarro-estadao.nyc3.cdn.digitaloceanspaces.com/wp-content/uploads/2023/08/04154650/HB20-Comfort-Plus-1160x653.jpg", "Prata", "Hyundai HB20 Hatch modelo 2022, por apenas R$62000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("HB20 Vision", "Hyundai", "2022", 65000, "Hatch", "https://cdn.awsli.com.br/600x450/562/562407/produto/310048662/retifica-de-motor-hyundai-hb20-vision-1-6-16v-flex-3o6yehdj66.png", "Vermelho", "Hyundai HB20 Vision Hatch modelo 2022, por apenas R$65000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("HB20S", "Hyundai", "2022", 70000, "Sedan", "https://grandbrasil.com.br/wp-content/uploads/2023/11/hb20s-platinumPlus-360-azulSapphire-05-1.png", "Azul", "Hyundai HB20S Sedan modelo 2022, por apenas R$70000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("HB20X", "Hyundai", "2023", 65000, "SUV", "https://resized-images.autoconf.com.br/1000x750/filters:format(jpg)/veiculos/fotos/334723/256302e6-c788-4b98-a4fa-a839ac4ae559.jpg", "Branco", "Hyundai HB20X SUV modelo 2023, por apenas R$65000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Hilux", "Toyota", "2023", 250000, "Picape", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBeyB0pEK2JjfF39RD3a6dmMQuFfUxxEjtA&s", "Branco", "Toyota Hilux Picape modelo 2023, por apenas R$250000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Hilux SR", "Toyota", "2023", 220000, "Picape", "https://media.toyota.com.br/64d653b1-248f-4a2c-870d-afb2c56ab83f.png", "Preto", "Toyota Hilux SR Picape modelo 2023, por apenas R$220000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Hilux SRV", "Toyota", "2022", 215000, "Picape", "https://production.autoforce.com/uploads/version/profile_image/9646/comprar-srv-4x4-automatico_eba607e42e.png", "Branco", "Toyota Hilux SRV Picape modelo 2022, por apenas R$215000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Himalayan", "Royal Enfield", "2023", 35000, "Adventure", "https://www.royalenfieldsp.com.br/img/motocicletas/himalayan/himalayan-mirage-silver-01.png", "Prata", "Royal Enfield Himalayan Adventure modelo 2023, por apenas R$35000!", 0, "MOTO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Honda CG 150 Titan", "Honda", "2023", 15000, "Street", "https://www.honda.com.br/motos/sites/hda/files/2021-03/CG%20150%20Cinza.jpg", "Prata", "Honda Honda CG 150 Titan Street modelo 2023, por apenas R$15000!", 0, "MOTO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("HR-V", "Honda", "2022", 105000, "SUV", "https://production.autoforce.com/uploads/version/profile_image/9409/model_main_webp_comprar-advance_ce7846fcef.png.webp", "Vinho", "Honda HR-V SUV modelo 2022, por apenas R$105000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("HR-V Touring", "Honda", "2023", 140000, "SUV", "https://www.daitan.com.br/img/modelos/hrv/touring/hrv-touring-branco-tafeta.jpg", "Branco", "Honda HR-V Touring SUV modelo 2023, por apenas R$140000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Huracán", "Lamborghini", "2014", 3500000, "Esportivo", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1zfp2QB4mqDCg7fmcS_ipxtHI-UyeabjZBA&s", "Verde", "Lamborghini Huracán Esportivo modelo 2014, por apenas R$3500000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("I Pace", "Jaguar ", "2023", 580000, "SUV", "https://media.autoexpress.co.uk/image/private/s--X-WVjvBW--/f_auto,t_content-image-full-desktop@1/v1692779637/autoexpress/2023/08/Jaguar%20I-Pace%202023%20facelift.jpg", "Preto", "Jaguar  I Pace SUV modelo 2023, por apenas R$580000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("i30 N Line", "Hyundai", "2023", 110000, "Hatch", "https://cdn.mattaki.com/hyundai/page-builder/content-pieces/cbdd040a-00e7-40f7-bd7e-59ec253442a3/e9a45ed1-694a-418e-a68d-6afd4366a321.webp", "Preto", "Hyundai i30 N Line Hatch modelo 2023, por apenas R$110000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("I5", "BMW", "2024", 760000, "Sedan", "https://cdn.motor1.com/images/mgl/0e7EKn/s1/bmw-i5-m60-xdrive-2023.webp", "Vermelho", "BMW I5 Sedan modelo 2024, por apenas R$760000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("ID.3", "Volkswagen", "2023", 300000, "Elétrico", "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEirsdZ-haZqeHG8-fLHz7fesWvVbzdESuX_evtTbSOxyDuOKtxgh3Qx5BfOsFlR8RPAit3iBbCnn9N_xSeZachBUJK2RIBUWq8DoYpyrV_2jzCEUhZno-0w0QxMv69Om7mn7hDnkPANDU5XEZMa1riC6hf7Btlh67aRMjtY7V2-Bj8PVNAL5TETmGHfCY2v/s2163/ID-3-Performance%20%289%29.jpg", "Prata", "Volkswagen ID.3 Elétrico modelo 2023, por apenas R$300000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Ioniq 5", "Hyundai", "2023", 250000, "Elétrico", "https://production.autoforce.com/uploads/version/profile_image/11604/comprar-ioniq-5-eletrico_79031a69b3.png", "Preto", "Hyundai Ioniq 5 Elétrico modelo 2023, por apenas R$250000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("iQ", "Toyota", "2015", 80000, "Micro", "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDL3gurPm9BJN9dZmED9kr7u421CrQ-39xlMtnal3FOFjiD7kbxY8npQvUch21AXVp8h9rubeqhXeRcDzUzqYq38OeolPJgT7plo6r5s7uSZD4er0RJZkZZG7etD3UCK0OJlg8Yt2HeAMN/?imgmax=800", "Branco", "Toyota iQ Micro modelo 2015, por apenas R$80000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Iron 883", "Harley-Davidson", "2021", 60000, "Cruiser", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI6R3haH3RGdQ8wUCAiB71khRONnbJoFaMmw&s", "Cinza", "Harley-Davidson Iron 883 Cruiser modelo 2021, por apenas R$60000!", 1, "MOTO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Jeep Renegade", "Jeep", "2021", 145000, "SUV", "https://mundodoautomovelparapcd.com.br/wp-content/uploads/2021/02/Jeep-Renegade-Sport-2021-07.jpg", "Branco", "Jeep Jeep Renegade SUV modelo 2021, por apenas R$145000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Jesko", "Koenigsegg", "2020", 15000000, "Superesportivo", "https://fotos-jornaldocarro-estadao.nyc3.cdn.digitaloceanspaces.com/wp-content/uploads/2020/08/27103150/Jesko_this.jpg", "Branco", "Koenigsegg Jesko Superesportivo modelo 2020, por apenas R$15000000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Jetta", "VolksWagen", "2018", 105000, "Sedan", "https://motorshow.com.br/wp-content/uploads/sites/2/2018/11/8_ms422_volkswagen-jetta1.jpg", "Branco", "VolksWagen Jetta Sedan modelo 2018, por apenas R$105000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Jimny", "Suzuki", "2022", 170000, "SUV", "https://image1.mobiauto.com.br/images/api/images/v1.0/51093308/transform/fl_progressive,f_webp,q_85,w_959", "Verde", "Suzuki Jimny SUV modelo 2022, por apenas R$170000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Ka", "Ford", "2022", 40000, "Hatch", "https://image1.mobiauto.com.br/images/api/images/v1.0/283582838/transform/fl_progressive,f_webp,q_80", "Branco", "Ford Ka Hatch modelo 2022, por apenas R$40000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Ka Sedan", "Ford", "2022", 55000, "Sedan", "https://image1.mobiauto.com.br/images/api/images/v1.0/49045529/transform/fl_progressive,f_webp,q_85,w_959,h_504", "Cinza", "Ford Ka Sedan Sedan modelo 2022, por apenas R$55000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Kicks", "Nissan", "2020", 100000, "SUV", "https://quatrorodas.abril.com.br/wp-content/uploads/2019/05/kicks-s-manual-linha-2020-2-source-e1559159659918.jpg?crop=1&resize=1212,909", "Marrom", "Nissan Kicks SUV modelo 2020, por apenas R$100000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Kicks Exclusive", "Nissan", "2023", 125000, "SUV", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxreLxpNBKVB6MXdMaJY0J2ugA8Bo_CP7C6g&s", "Cinza", "Nissan Kicks Exclusive SUV modelo 2023, por apenas R$125000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Kwid", "Renault", "2022", 50000, "Hatch", "https://www.karvi.com.br/_next/image/?url=https%3A%2F%2Fdjdnloyvqzzd3.cloudfront.net%2Fstatic%2Fgallery%2Fbr%2Fdesktop%2Frenault_kwid_2022_perfil_frente.jpg&w=1440&q=90", "Branco", "Renault Kwid Hatch modelo 2022, por apenas R$50000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("L200 Triton", "Mitsubishi", "2022", 160000, "Picape", "https://multimedia-api.mitsubishimotors.com.br/multimedia/api/images/v1.0/4049/transform/t_crop,2Cw_auto,2Ch_auto,fl_progressive,f_webp,q_auto", "Cinza", "Mitsubishi L200 Triton Picape modelo 2022, por apenas R$160000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("L200 Triton GLX", "Mitsubishi", "2023", 180000, "Picape", "https://production.autoforce.com/uploads/version/profile_image/7318/model_main_webp_comprar-glx-mt_3182974991.png.webp", "Cinza", "Mitsubishi L200 Triton GLX Picape modelo 2023, por apenas R$180000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("L200 Triton Sport", "Mitsubishi", "2022", 175000, "Picape", "https://image1.mobiauto.com.br/images/api/images/v1.0/111023697/transform/fl_progressive,f_webp,q_80", "Cinza", "Mitsubishi L200 Triton Sport Picape modelo 2022, por apenas R$175000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Levante", "Maserati", "2022", 690000, "Esportivo", "https://file.kelleybluebookimages.com/kbb/base/evox/CP/14899/2022-Maserati-Levante-front_14899_032_1825x825_BAM_cropped.png", "Branco", "Maserati Levante Esportivo modelo 2022, por apenas R$690000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("LFA", "Lexus", "2012", 3500000, "Esportivo", "https://cdn.motor1.com/images/mgl/zl06E/s1/r-25-milhoes-comprador-do-unico-lexus-lfa-no-brasil-conhecera-a-fabrica-no-japao.webp", "Branco", "Lexus LFA Esportivo modelo 2012, por apenas R$3500000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Logan", "Renault", "2022", 58000, "Sedan", "https://cdn.motor1.com/images/mgl/7xGZq/s1/novo-renault-logan-2022---projecao.webp", "Prata", "Renault Logan Sedan modelo 2022, por apenas R$58000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Logan Expression", "Renault", "2022", 60000, "Sedan", "https://www.autossegredos.com.br/wp-content/webp-express/webp-images/uploads/2020/07/PROJECAO-NOVO-RENAULT-LOGAN-2022-1-1024x652.jpg.webp", "Vermelho", "Renault Logan Expression Sedan modelo 2022, por apenas R$60000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Logan Stepway", "Renault", "2023", 67000, "Sedan", "https://cdn.motor1.com/images/mgl/6n80E/s3/renault-logan-stepway-2022---projecao.jpg", "Branco", "Renault Logan Stepway Sedan modelo 2023, por apenas R$67000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Mistral", "Bugatti", "2022", 85000000, "Superesportivo", "https://cdn.motor1.com/images/mgl/BXXw8A/s1/2024-bugatti-mistral.jpg", "Preto", "Bugatti Mistral Superesportivo modelo 2022, por apenas R$85000000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Mobi", "Fiat", "2021", 35000, "Hatch", "https://uploads.vrum.com.br/2022/12/cc312323-fiat-mobi-velocity-modelo-2018-branco-de-frente-estatico.jpg", "Branco", "Fiat Mobi Hatch modelo 2021, por apenas R$35000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Mobi Way", "Fiat", "2021", 45000, "Hatch", "https://uploads.vrum.com.br/2022/12/cc312323-fiat-mobi-velocity-modelo-2018-branco-de-frente-estatico.jpg", "Branco", "Fiat Mobi Way Hatch modelo 2021, por apenas R$45000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Model 3", "Tesla", "2023", 350000, "Elétrico", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCEbuOWqJ8CAD-nOSAXCMLBOI3CuaZQMH9vw&s", "Branco", "Tesla Model 3 Elétrico modelo 2023, por apenas R$350000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Montana", "Chevrolet", "2021", 85000, "Picape", "https://quatrorodas.abril.com.br/wp-content/uploads/2021/01/Nova-Chevrolet-Montana-e1609862459917.jpg?quality=70&strip=info", "Azul", "Chevrolet Montana Picape modelo 2021, por apenas R$85000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Montana LTZ", "Chevrolet", "2021", 95000, "Picape", "https://www.chevroletnova.com.br/images/versoes/fotos/2024/03/ltz_17111383991.jpg", "Preto", "Chevrolet Montana LTZ Picape modelo 2021, por apenas R$95000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("MT-07", "Yamaha", "2023", 45000, "Naked", "https://cdn.motor1.com/images/mgl/qzOBv/s1/2021-yamaha-mt-07-team-yamaha-blue.jpg", "Azul", "Yamaha MT-07 Naked modelo 2023, por apenas R$45000!", 0, "MOTO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Mustang", "Ford", "2022", 300000, "Esportivo", "https://autoentusiastas.com.br/ae/wp-content/uploads/2021/12/Ford-Mustang-Shelby-GT-500KR-2022-2.jpg", "Azul", "Ford Mustang Esportivo modelo 2022, por apenas R$300000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Mustang Mach-E", "Ford", "2023", 340000, "Elétrico", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmLes9E789jYE8fpSVoLg8k4dO3tqZ1HYK4g&s", "Branco", "Ford Mustang Mach-E Elétrico modelo 2023, por apenas R$340000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Nevera", "Rimac", "2023", 6000000, "Elétrico", "https://cdn.motor1.com/images/mgl/W8o72O/s1/rimac-nevera-sets-23-records-at-the-automotive-testing-papenburg-in-germany.webp", "Preto", "Rimac Nevera Elétrico modelo 2023, por apenas R$6000000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Ninja 400", "Kawasaki", "2024", 42000, "Esportiva", "https://kawasaki.m3parts.com.br/arquivos/1705004947_24ex400l_44sgn1drf3cg_a.jpg", "Verde", "Kawasaki Ninja 400 Esportiva modelo 2024, por apenas R$42000!", 0, "MOTO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Niro", "Kia", "2022", 150000, "SUV", "https://knorte.com.br/wp-content/uploads/2022/10/kia-cores-niro-cr5-vermelho-metalico-scaled.jpg", "Vermelho", "Kia Niro SUV modelo 2022, por apenas R$150000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Nivus", "Volkswagen", "2023", 110000, "SUV", "https://image1.mobiauto.com.br/images/api/images/v1.0/315407494/transform/fl_progressive,f_webp,q_70,w_592", "cinza", "Volkswagen Nivus SUV modelo 2023, por apenas R$110000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Nivus Highline", "Volkswagen", "2023", 120000, "SUV", "https://blog.carrera.com.br/wp-content/uploads/2023/07/Nivus-Highline-2024-II.jpg", "Branco", "Volkswagen Nivus Highline SUV modelo 2023, por apenas R$120000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Onix", "Chevrolet", "2022", 62000, "Hatch", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0FyJ_QKqqg6MdZOXh1w-4WQVFj3PuaKwiQQ&s", "Azul", "Chevrolet Onix Hatch modelo 2022, por apenas R$62000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Onix Activ", "Chevrolet", "2023", 63000, "SUV", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd3Mf6ysmdxDuBkqBoA3Kq5Ksa4iE1G4k3EA&s", "Branco", "Chevrolet Onix Activ SUV modelo 2023, por apenas R$63000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Onix Plus", "Chevrolet", "2023", 75000, "Hatch", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvJNn79ENOrk_St74Wqg-OHIu2xUqoy7VE_w&s", "Preto", "Chevrolet Onix Plus Hatch modelo 2023, por apenas R$75000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Opala Comodoro", "Chevrolet", "1979", 24520, "Sedan", "https://lartbr.com.br/wp-content/uploads/2022/07/opaladiplodoro-opalacomodoro-opaladiplomata-3.jpg", "Verde", "Chevrolet Opala Comodoro Sedan modelo 1979, por apenas R$24520!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Oroch", "Renault", "2020", 95000, "Picape", "https://production.autoforce.com/uploads/version/profile_image/3559/comprar-dynamique-2-0-manual_55df99508d.png", "Vermelho", "Renault Oroch Picape modelo 2020, por apenas R$95000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Oroch Outsider", "Renault", "2020", 105000, "Picape", "https://brfrance.com.br/uploads/products/versions/renault-banner-990x600-oroch-outsider-cinza-lune.png", "Cinza", "Renault Oroch Outsider Picape modelo 2020, por apenas R$105000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Oroch Sense", "Nissan", "2023", 115000, "Picape", "https://blog.carrera.com.br/wp-content/uploads/2023/07/Nova-Oroch-Outsider-2023-I-1024x610.jpg", "Cinza", "Nissan Oroch Sense Picape modelo 2023, por apenas R$115000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("P72", "De Tomaso", "2023", 3000000, "Esportivo", "https://www.planetcarsz.com/img/carros/2022/06/de-tomaso-p72-2023-19-20220604143557-1920x1080.jpg", "Azul", "De Tomaso P72 Esportivo modelo 2023, por apenas R$3000000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Palio", "Fiat", "2023", 40000, "Hatch", "https://www.agoramotor.com.br/wp-content/uploads/2022/07/fiat-palio-2023-frente.jpg", "Prata", "Fiat Palio Hatch modelo 2023, por apenas R$40000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("PCX 160", "Honda", "2024", 25000, "Scooter", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTr8UmJ6slIPUkQ7cHgxYRyETtQzAp57TYP4Q&s", "Azul", "Honda PCX 160 Scooter modelo 2024, por apenas R$25000!", 0, "MOTO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Polo", "Volkswagen", "2022", 70000, "Hatch", "https://i0.statig.com.br/bancodeimagens/imgalta/cj/ax/2p/cjax2pslxxo032tjf43ga5htl.jpg", "Azul", "Volkswagen Polo Hatch modelo 2022, por apenas R$70000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Prisma", "Chevrolet", "2012", 25000, "SEDAN", "https://cdn.motor1.com/images/mgl/Ye4bJ/s1/4x3/chevrolet-prisma-advantage.webp", "Prata", "Chevrolet Prisma SEDAN modelo 2012, por apenas R$25000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Pulse", "Fiat", "2022", 80000, "SUV", "https://quatrorodas.abril.com.br/wp-content/uploads/2021/10/Fiat-Pulse-Impetus-Turbo-200-1.0-CVT-2022-11.jpg?quality=70&strip=info&w=920&w=636", "Azul", "Fiat Pulse SUV modelo 2022, por apenas R$80000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Pulse Audace", "Fiat", "2023", 105000, "SUV", "https://production.autoforce.com/uploads/version/profile_image/7984/comprar-audace-turbo-200_fca8252609.png", "Vermelho", "Fiat Pulse Audace SUV modelo 2023, por apenas R$105000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Q3", "Audi", "2019", 300000, "SUV", "https://mundodoautomovelparapcd.com.br/wp-content/uploads/2019/07/novo-audi-Q3-2019-05.jpg", "Branco", "Audi Q3 SUV modelo 2019, por apenas R$300000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("R1T", "Rivian", "2023", 800000, "Picape Elétrica", "https://img.odcdn.com.br/wp-content/uploads/2021/12/rivian-r1t.jpg", "Azul", "Rivian R1T Picape Elétrica modelo 2023, por apenas R$800000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("R8", "Audi", "2024", 2000000, "Esportivo", "https://cdn.motor1.com/images/mgl/BXQEXR/s3/audi-r8-coupe-v10-performance-rwd-at-laguna-seca.jpg", "Cinza", "Audi R8 Esportivo modelo 2024, por apenas R$2000000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("RAM 2500", "RAM", "2023", 400000, "Picape", "https://cdn.motor1.com/images/mgl/Akm1e9/s1/ram-2500-laramie-2023.jpg", "Branco", "RAM RAM 2500 Picape modelo 2023, por apenas R$400000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Ranger", "Ford", "2023", 190000, "Picape", "https://s2-autoesporte.glbimg.com/JJmD0-6WepluaxOZnc-V-dGaDnw=/0x0:1300x802/924x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2021/4/h/gQdh2KRliNSrDnZmql1Q/nextgenranger-wildtrak-front-3qtr-static-tarmac-2.jpg", "Laranja", "Ford Ranger Picape modelo 2023, por apenas R$190000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Ranger XLS", "Ford", "2023", 200000, "Picape", "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi36LyCciM0R85R9ByIQajK3BRqgk-5abL5QTBULoLchPj15JK7FFqGYOH4R0-hhc_pdvy1tEX5JPj4Att5cHaSosTrYUYQoXNP2ZJnV3hOKGEtnfngxHPGPg2dk1OUPOaXANcY5NiMzPxHms9w3YDTrZh2baA5DKume1hBI30qkRtlCPr0fexstODvOwI/s1574/Nova%20Ford%20Ranger%20XLS%202.0%204X2_1.jpg", "Branco", "Ford Ranger XLS Picape modelo 2023, por apenas R$200000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Ranger XLT", "Ford", "2023", 205000, "Picape", "https://live.dealer-asset.co/images/br1001/product/paintSwatch/vehicle/ford-brasil-nova-geracao-ranger-xlt-branco-artico.png?s=1024", "Branco", "Ford Ranger XLT Picape modelo 2023, por apenas R$205000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Rapid Cross", "Volkswagen", "2023", 75000, "SUV", "https://quatrorodas.abril.com.br/wp-content/uploads/2022/05/volkswagen_t-cross_301.jpeg?crop=1&resize=1212,909", "Dourado", "Volkswagen Rapid Cross SUV modelo 2023, por apenas R$75000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Renegade", "Jeep", "2023", 140000, "SUV", "https://s2-autoesporte.glbimg.com/3ZQ5YB4dIMnZYoBMnYTGXOOHR-E=/0x0:1300x731/924x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2022/L/Y/baWTZ6RAatG6K9jiSTiw/novo-jeep-renegade-trailhawk-2-.jpg", "Laranja", "Jeep Renegade SUV modelo 2023, por apenas R$140000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Renegade Limited", "Jeep", "2023", 170000, "SUV", "https://www.automaistv.com.br/wp-content/uploads/2022/02/jeep_renegade_trailhawk_t270_4_4_71_edited-750x450.jpg", "Laranja", "Jeep Renegade Limited SUV modelo 2023, por apenas R$170000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Renegade Longitude", "Jeep", "2023", 150000, "SUV", "https://production.autoforce.com/uploads/version/profile_image/8113/comprar-longitude_eb3258d504.png", "Verde", "Jeep Renegade Longitude SUV modelo 2023, por apenas R$150000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("RS6", "Audi", "2022", 1175000, "Perua", "https://cdn.motor1.com/images/mgl/g4MJbN/s1/audi-rs6-avant-performance.webp", "Preto", "Audi RS6 Perua modelo 2022, por apenas R$1175000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("S10", "Chevrolet", "2021", 180000, "Picape", "https://fotos-jornaldocarro-estadao.nyc3.cdn.digitaloceanspaces.com/wp-content/uploads/2020/10/26073011/Chevrolet-S10-High-Country-3.jpg", "Branco", "Chevrolet S10 Picape modelo 2021, por apenas R$180000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("S10 LT", "Chevrolet", "2023", 190000, "Picape", "https://production.autoforce.com/uploads/version/profile_image/7385/comprar-4x4-2-8-diesel-lt-pacote-r7n_1f436b2566.png", "Azul", "Chevrolet S10 LT Picape modelo 2023, por apenas R$190000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("S10 LTZ", "Chevrolet", "2022", 195000, "Picape", "https://revistaautomotivo.com.br/wp-content/uploads/2021/04/chevrolets10-e1619102205139.jpg", "Branco", "Chevrolet S10 LTZ Picape modelo 2022, por apenas R$195000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Sandero", "Renault", "2021", 52000, "Hatch", "https://www.webmotors.com.br/imagens/prod/346363/RENAULT_SANDERO_2.0_16V_HIFLEX_RS_MANUAL_34636305391606463.webp", "Vermelho", "Renault Sandero Hatch modelo 2021, por apenas R$52000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Saveiro", "Volkswagen", "2022", 90000, "Picape", "https://cdn.motor1.com/images/mgl/q4ogR/s1/4x3/volkswagen-saveiro-2022.webp", "Azul", "Volkswagen Saveiro Picape modelo 2022, por apenas R$90000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Saveiro Robust", "Volkswagen", "2022", 105000, "Picape", "https://cdn.motor1.com/images/mgl/q4ogR/s1/volkswagen-saveiro-2022.webp", "Azul", "Volkswagen Saveiro Robust Picape modelo 2022, por apenas R$105000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Saveiro Trendline", "Volkswagen", "2023", 90000, "Picape", "https://s3.sa-east-1.amazonaws.com/revista.mobiauto/Volkswagen/Saveiro/2023/VW+Saveiro+Trendline+CS+2023.jpg", "Branco", "Volkswagen Saveiro Trendline Picape modelo 2023, por apenas R$90000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Scrambler", "Ducati", "2022", 65000, "Scrambler", "https://media.triumphmotorcycles.co.uk/image/upload/q_auto:eco/sitecoremedialibrary/media-library/images/motorcycles/modern-classics/my21/dr-ds-d74%20-%20scrambler%201200/base%20images/scrambler%201200%20xe/updated/scrambler-1200-xe-green-and-black-righths-1100x629.png", "Verde", "Ducati Scrambler Scrambler modelo 2022, por apenas R$65000!", 0, "MOTO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Sentra", "Nissan", "2022", 80000, "Sedan", "https://motorshow.com.br/wp-content/uploads/sites/2/2023/03/novo-nissan-sentra-exclusive-1-scaled-e1678976080663.jpg", "Branco", "Nissan Sentra Sedan modelo 2022, por apenas R$80000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("SF90", "Ferrari", "2024", 5525600, "Superesportivo", "https://miamiimports.com.br/wp-content/uploads/2024/03/FERRARI-SF90-STRADALE-FRENTE.png", "Vermelho", "Ferrari SF90 Superesportivo modelo 2024, por apenas R$5525600!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Silverado", "Chevrolet", "2021", 350000, "Picape", "https://motorshow.com.br/wp-content/uploads/sites/2/2020/08/2020-chevrolet-silverado-diesel-081.jpg", "Vermelho", "Chevrolet Silverado Picape modelo 2021, por apenas R$350000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Spin", "Chevrolet", "2022", 85000, "SUV", "https://cdn.motor1.com/images/mgl/AvjxO/s1/chevrolet-spin-premier-2022.jpg", "Branco", "Chevrolet Spin SUV modelo 2022, por apenas R$85000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Spin Activ 7", "Chevrolet", "2024", 120000, "Minivan", "https://production.autoforce.com/uploads/version/profile_image/9255/comprar-activ-7-1-8-at-pacote-r7l_2f5c5ab79c.png", "Prata", "Chevrolet Spin Activ 7 Minivan modelo 2024, por apenas R$120000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Sportage", "Kia", "2023", 145000, "SUV", "https://mundodoautomovelparapcd.com.br/wp-content/uploads/2022/07/kia-sportage.jpg", "Cinza", "Kia Sportage SUV modelo 2023, por apenas R$145000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Strada", "Fiat", "2022", 70000, "Picape", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZbgj2jSl_c9M5IOgOIpct2o6_TVbqVnumaQ&s", "Branco", "Fiat Strada Picape modelo 2022, por apenas R$70000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Strada Volcano", "Fiat", "2023", 95000, "Picape", "https://production.autoforce.com/uploads/version/profile_image/8039/model_main_webp_comprar-volcano-cd-1-3_ac4b64b16a.png.webp", "Vermelho", "Fiat Strada Volcano Picape modelo 2023, por apenas R$95000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Strada Working", "Fiat", "2023", 85000, "Picape", "https://img1.icarros.com/dbimg/imgadicionalnoticia/4/116206_1", "Cinza", "Fiat Strada Working Picape modelo 2023, por apenas R$85000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Supra", "Toyota", "1994", 1500000, "Esportivo", "https://image.webmotors.com.br/_fotos/anunciousados/gigante/2024/202410/20241021/toyota-supra-3-0-24v-biturbo-gasolina-4p-manual-wmimagem15091609238.webp?s=fill&w=1920&h=1440&q=75", "Preto", "Toyota Supra Esportivo modelo 1994, por apenas R$1500000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("T-Cross", "Volkswagen", "2021", 120000, "SUV", "https://s2-autoesporte.glbimg.com/RG-L4ZEaNdZFksbr8IJP1zxmL5A=/0x0:620x413/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2020/V/8/H8hv5pSb2Wsy3aj7lLgQ/2020-08-06-46b4943d-32fe-4f7f-b9a5-6f83fc04920c.jpeg", "Branco", "Volkswagen T-Cross SUV modelo 2021, por apenas R$120000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("T-Cross Comfortline", "Volkswagen", "2023", 120000, "SUV", "https://mundodoautomovelparapcd.com.br/wp-content/uploads/2022/11/Volkswagen-T-Cross-Comfortline-2023-1280x720.jpg", "Cinza", "Volkswagen T-Cross Comfortline SUV modelo 2023, por apenas R$120000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("T-Cross Highline", "Volkswagen", "2023", 125000, "SUV", "https://p2.trrsf.com/image/fget/cf/774/0/images.terra.com/2022/10/19/tcross-high-s1gqac6c82lu.png", "Preto", "Volkswagen T-Cross Highline SUV modelo 2023, por apenas R$125000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Tiguan", "Volkswagen", "2023", 170000, "SUV", "https://cdn.motor1.com/images/mgl/zx42Aq/s1/volkswagen-tiguan-allspace-2023.jpg", "Vermelho", "Volkswagen Tiguan SUV modelo 2023, por apenas R$170000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Toro Freedom", "Fiat", "2023", 140000, "Picape", "https://production.autoforce.com/uploads/version/profile_image/7974/comprar-freedom-turbo-270-flex-at6_61bb8f0646.png", "Prata", "Fiat Toro Freedom Picape modelo 2023, por apenas R$140000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Tracker", "Chevrolet", "2022", 95000, "SUV", "https://www.portalin.com.br/wp-content/uploads/2021/12/novo_tracker__novo_tracker_ltz_2022_250.jpg", "Vermelho", "Chevrolet Tracker SUV modelo 2022, por apenas R$95000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Tracker Premier", "Chevrolet", "2022", 170000, "SUV", "https://motorshow.com.br/wp-content/uploads/sites/2/2022/12/chevrolet-tracker-premier-1-1-e1671017526126.jpg", "Cinza", "Chevrolet Tracker Premier SUV modelo 2022, por apenas R$170000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Tucson", "Hyundai", "2021", 150000, "SUV", "https://fotos-jornaldocarro-estadao.nyc3.cdn.digitaloceanspaces.com/wp-content/uploads/2020/09/15094520/Hyundai-Tucson-2021-4-1160x653.jpg", "Azul", "Hyundai Tucson SUV modelo 2021, por apenas R$150000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Twizy", "Renault", "2023", 80000, "Elétrico", "https://uploads.vrum.com.br/2023/07/46861aa8-renault-twizy-frente-1024x683.jpg", "Branco", "Renault Twizy Elétrico modelo 2023, por apenas R$80000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Up!", "Volkswagen", "2022", 42000, "Hatch", "https://fotos-jornaldocarro-estadao.nyc3.cdn.digitaloceanspaces.com/wp-content/uploads/2022/08/24175305/vw-e-up.jpg", "Azul", "Volkswagen Up! Hatch modelo 2022, por apenas R$42000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("V-Strom 650XT", "Suzuki", "2023", 50000, "Adventure", "https://www.webmotors.com.br/wp-content/uploads/2022/09/15161322/Suzuki-V-Strom-650XT-1.jpg", "Preto", "Suzuki V-Strom 650XT Adventure modelo 2023, por apenas R$50000!", 1, "MOTO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Vantage GT4", "Aston Martin", "2024", 2249000, "Superesportivo", "https://cdn.motor1.com/images/mgl/Akg9l6/s2/aston-martin-vantage-gt4.webp", "Verde", "Aston Martin Vantage GT4 Superesportivo modelo 2024, por apenas R$2249000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Versa", "Nissan", "2021", 65000, "Sedan", "https://fotos-jornaldocarro-estadao.nyc3.cdn.digitaloceanspaces.com/wp-content/uploads/2020/10/28074647/ALTA-6740-scaled.jpg", "Vermelho", "Nissan Versa Sedan modelo 2021, por apenas R$65000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Versa Advance", "Nissan", "2021", 75000, "Sedan", "https://s3-sa-east-1.amazonaws.com/revista.mobiauto/ImagensSUVs/Nissan+Versa+2021/Oficiais/Versa+2021+Advance/Nissan+Versa+2021+Advance+CVT+frente.jpg", "Prata", "Nissan Versa Advance Sedan modelo 2021, por apenas R$75000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Versa Adventure", "Nissan", "2023", 72000, "SUV", "https://www.globonissan.com.br/imagens/img_veic/veiculonissan619-2023.png", "Cinza", "Nissan Versa Adventure SUV modelo 2023, por apenas R$72000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Veyron", "Bugatti", "2011", 13240000, "Superesportivo", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Bugatti_Veyron_16.4_%E2%80%93_Frontansicht_%281%29%2C_5._April_2012%2C_D%C3%BCsseldorf.jpg/640px-Bugatti_Veyron_16.4_%E2%80%93_Frontansicht_%281%29%2C_5._April_2012%2C_D%C3%BCsseldorf.jpg", "Preto", "Bugatti Veyron Superesportivo modelo 2011, por apenas R$13240000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Virtus", "Volkswagen", "2023", 70000, "Sedan", "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh7nJxuerB7bFmUgEhQ3ipr0voeJCgC4eUXIEpvdnuTJzpwezPQZMLE5VWG9g5FLUsoOhrfs6CAcslVuASEphvIjcgcnoBinTdpYbXO_uVJP3m53kospYbx6pcbmxQPPyjOw5R7d-__jTgl9rStcKbihC2NWGbaqEAMzHqOVKbQjUXMAA_6cCEVtNiWfw/s2560/VW-Virtus-2023%20%283%29.JPG", "Prata", "Volkswagen Virtus Sedan modelo 2023, por apenas R$70000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Virtus Comfortline", "Volkswagen", "2023", 75000, "Sedan", "https://quatrorodas.abril.com.br/wp-content/uploads/2023/02/Novo-Virtus-Exclusive.jpg?quality=70&strip=info", "Preto", "Volkswagen Virtus Comfortline Sedan modelo 2023, por apenas R$75000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("X-Trail", "Nissan", "2021", 155000, "SUV", "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjDH19vTF8q0GtUa0liPjDDnx6xQr2tKJB2trTzMKAYFYmv7XwA8XIhIWcLFQvFmghtg7v1In83AN9IQv-jpqZfvFCnoVNnZjuclk0h3AkXyEJPwOpvH_Jk8K95DOvpsxs9KuPSBKKx8-aq/s1600/Nissan-X-Trail-2021+%252810%2529.jpg", "Vermelho", "Nissan X-Trail SUV modelo 2021, por apenas R$155000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Yaris", "Toyota", "2023", 70000, "Sedan", "https://garagem360.com.br/wp-content/uploads/2022/02/Yaris-2023_50.jpg", "Cinza", "Toyota Yaris Sedan modelo 2023, por apenas R$70000!", 0, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Yaris Cross", "Toyota", "2023", 90000, "SUV", "https://dicas.olx.com.br/wp-content/uploads/2024/08/yaris-cross.jpg", "Prata", "Toyota Yaris Cross SUV modelo 2023, por apenas R$90000!", 1, "CARRO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("YBR 125", "Yamaha", "2022", 13000, "Street", "https://www.agoramotors.com.br/wp-content/uploads/2021/09/Yamaha-YBR-Factor-2022-capa.jpg", "Vermelho", "Yamaha YBR 125 Street modelo 2022, por apenas R$13000!", 0, "MOTO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Z125 Pro", "Kawasaki", "2021", 20000, "Street", "https://storage.kawasaki.eu/public/kawasaki.eu/en-EU/model/21MY_Z125_GN1_STU__1_.png", "Verde", "Kawasaki Z125 Pro Street modelo 2021, por apenas R$20000!", 0, "MOTO");
insert into carros (modelo_carros, marca_carros, ano_carros, preco_carros, categoria_carros, imagem_carros, cor_carros, descricao_carros, promocao, classe_carros) values("Z4 M40i", "BMW", "2024", 330000, "Esportivo", "https://vehicle-images.dealerinspire.com/52c7-18003207/WBAHF9C04RWY37083/3f7d2496be45786ba5d6f63c364fd010.jpg", "Preto", "BMW Z4 M40i Esportivo modelo 2024, por apenas R$330000!", 1, "CARRO");

--
-- Índices para tabelas despejadas
--

--
-- Índices de tabela `carros`
--
ALTER TABLE `carros`
  ADD PRIMARY KEY (`id_carros`);

--
-- AUTO_INCREMENT para tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `carros`
--
ALTER TABLE `carros`
  MODIFY `id_carros` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
